branch-defaults:
  default:
    environment: ordermicroser1-dev
    group_suffix: null
global:
  application_name: ordermicroser1
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  repository: null
  sc: null
