branch-defaults:
  default:
    environment: prodmicro2
    group_suffix: null
global:
  application_name: productsmicroservice
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  sc: null
