let actionConstants  = () => {
	

	return {

		"SET_USER_INFO" : "SET_USER_INFO",
		"SET_USER_LOGGED_IN" : "SET_USER_LOGGED_IN",
		"ADD_NOTIFICATION" : "ADD_NOTIFICATION",
		"SET_NOTIFICATION_TRIGGER_FLAG" : "SET_NOTIFICATION_TRIGGER_FLAG",
		"SET_FLAGS" : "SET_FLAGS",
		"SET_GROCERIES" : "SET_GROCERIES",
		"SET_SINGLE_GROCERY_INFO_FOR_USER" : "SET_SINGLE_GROCERY_INFO_FOR_USER",
		"SET_CUSTOMERACCOUNTS" : "SET_CUSTOMERACCOUNTS",
		"SET_USER_PURCHASE_HISTORY" : "SET_USER_PURCHASE_HISTORY"

	};

};

export default actionConstants();